# This file was generated by GoReleaser. DO NOT EDIT.
class HelmFreeze < Formula
  desc "Freeze your charts in the wished versions"
  homepage ""
  version "0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Qovery/helm-freeze/releases/download/v0.2/helm-freeze_0.2_darwin_amd64.tar.gz"
    sha256 "6debb3339506dfa970d27643cb14fedae7c017f4418b2886c5f3212b7006935c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/helm-freeze/releases/download/v0.2/helm-freeze_0.2_linux_amd64.tar.gz"
      sha256 "5e8261d17200062952f832c137307acee088d381e29a32d52da745a8fba19920"
    end
  end

  def install
    bin.install "helm-freeze"
  end
end
