# This file was generated by GoReleaser. DO NOT EDIT.
class HelmFreeze < Formula
  desc "Freeze your charts in the wished versions"
  homepage ""
  version "0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Qovery/helm-freeze/releases/download/v0.1/helm-freeze_0.1_darwin_amd64.tar.gz"
    sha256 "06e425b2c38822b0200fa4b2611c047a916d67f1db553a851adb13058c3de09a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Qovery/helm-freeze/releases/download/v0.1/helm-freeze_0.1_linux_amd64.tar.gz"
      sha256 "babcb7f465b827270c3fef58133f8d5f1b2ca77038c07ce1d29fed391eae9534"
    end
  end

  def install
    bin.install "helm-freeze"
  end
end
